-- 取り札（下の句の札）の画像URL
--
-- 出どころ: ウィキメディア・コモンズの「SVGs of Torifuda」
--   例) https://commons.wikimedia.org/wiki/File:Torifuda_017.svg
--   ライセンス: CC0（パブリックドメインと同等。自由に利用できる）
--
-- 実行方法（apps/api ディレクトリで）:
--   set -a; . ./.env; set +a
--   PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \\
--     -f src/chihaya/sql/seed_torifuda.sql

UPDATE poems SET torifuda_url = t.url, updated_at = now()
  FROM (VALUES
  (1, 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Torifuda_001.svg'),
  (2, 'https://upload.wikimedia.org/wikipedia/commons/5/50/Torifuda_002.svg'),
  (3, 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Torifuda_003.svg'),
  (4, 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Torifuda_004.svg'),
  (5, 'https://upload.wikimedia.org/wikipedia/commons/4/41/Torifuda_005.svg'),
  (6, 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Torifuda_006.svg'),
  (7, 'https://upload.wikimedia.org/wikipedia/commons/7/77/Torifuda_007.svg'),
  (8, 'https://upload.wikimedia.org/wikipedia/commons/9/99/Torifuda_008.svg'),
  (9, 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Torifuda_009.svg'),
  (10, 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Torifuda_010.svg'),
  (11, 'https://upload.wikimedia.org/wikipedia/commons/1/11/Torifuda_011.svg'),
  (12, 'https://upload.wikimedia.org/wikipedia/commons/9/91/Torifuda_012.svg'),
  (13, 'https://upload.wikimedia.org/wikipedia/commons/9/93/Torifuda_013.svg'),
  (14, 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Torifuda_014.svg'),
  (15, 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Torifuda_015.svg'),
  (16, 'https://upload.wikimedia.org/wikipedia/commons/d/de/Torifuda_016.svg'),
  (17, 'https://upload.wikimedia.org/wikipedia/commons/0/05/Torifuda_017.svg'),
  (18, 'https://upload.wikimedia.org/wikipedia/commons/2/25/Torifuda_018.svg'),
  (19, 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Torifuda_019.svg'),
  (20, 'https://upload.wikimedia.org/wikipedia/commons/6/69/Torifuda_020.svg'),
  (21, 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Torifuda_021.svg'),
  (22, 'https://upload.wikimedia.org/wikipedia/commons/3/33/Torifuda_022.svg'),
  (23, 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Torifuda_023.svg'),
  (24, 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Torifuda_024.svg'),
  (25, 'https://upload.wikimedia.org/wikipedia/commons/8/80/Torifuda_025.svg'),
  (26, 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Torifuda_026.svg'),
  (27, 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Torifuda_027.svg'),
  (28, 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Torifuda_028.svg'),
  (29, 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Torifuda_029.svg'),
  (30, 'https://upload.wikimedia.org/wikipedia/commons/0/05/Torifuda_030.svg'),
  (31, 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Torifuda_031.svg'),
  (32, 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Torifuda_032.svg'),
  (33, 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Torifuda_033.svg'),
  (34, 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Torifuda_034.svg'),
  (35, 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Torifuda_035.svg'),
  (36, 'https://upload.wikimedia.org/wikipedia/commons/7/79/Torifuda_036.svg'),
  (37, 'https://upload.wikimedia.org/wikipedia/commons/5/52/Torifuda_037.svg'),
  (38, 'https://upload.wikimedia.org/wikipedia/commons/4/47/Torifuda_038.svg'),
  (39, 'https://upload.wikimedia.org/wikipedia/commons/8/82/Torifuda_039.svg'),
  (40, 'https://upload.wikimedia.org/wikipedia/commons/1/12/Torifuda_040.svg'),
  (41, 'https://upload.wikimedia.org/wikipedia/commons/d/df/Torifuda_041.svg'),
  (42, 'https://upload.wikimedia.org/wikipedia/commons/1/13/Torifuda_042.svg'),
  (43, 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Torifuda_043.svg'),
  (44, 'https://upload.wikimedia.org/wikipedia/commons/6/64/Torifuda_044.svg'),
  (45, 'https://upload.wikimedia.org/wikipedia/commons/1/13/Torifuda_045.svg'),
  (46, 'https://upload.wikimedia.org/wikipedia/commons/9/98/Torifuda_046.svg'),
  (47, 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Torifuda_047.svg'),
  (48, 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Torifuda_048.svg'),
  (49, 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Torifuda_049.svg'),
  (50, 'https://upload.wikimedia.org/wikipedia/commons/1/10/Torifuda_050.svg'),
  (51, 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Torifuda_051.svg'),
  (52, 'https://upload.wikimedia.org/wikipedia/commons/8/87/Torifuda_052.svg'),
  (53, 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Torifuda_053.svg'),
  (54, 'https://upload.wikimedia.org/wikipedia/commons/6/69/Torifuda_054.svg'),
  (55, 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Torifuda_055.svg'),
  (56, 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Torifuda_056.svg'),
  (57, 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Torifuda_057.svg'),
  (58, 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Torifuda_058.svg'),
  (59, 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Torifuda_059.svg'),
  (60, 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Torifuda_060.svg'),
  (61, 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Torifuda_061.svg'),
  (62, 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Torifuda_062.svg'),
  (63, 'https://upload.wikimedia.org/wikipedia/commons/8/88/Torifuda_063.svg'),
  (64, 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Torifuda_064.svg'),
  (65, 'https://upload.wikimedia.org/wikipedia/commons/6/63/Torifuda_065.svg'),
  (66, 'https://upload.wikimedia.org/wikipedia/commons/1/15/Torifuda_066.svg'),
  (67, 'https://upload.wikimedia.org/wikipedia/commons/5/58/Torifuda_067.svg'),
  (68, 'https://upload.wikimedia.org/wikipedia/commons/2/29/Torifuda_068.svg'),
  (69, 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Torifuda_069.svg'),
  (70, 'https://upload.wikimedia.org/wikipedia/commons/6/65/Torifuda_070.svg'),
  (71, 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Torifuda_071.svg'),
  (72, 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Torifuda_072.svg'),
  (73, 'https://upload.wikimedia.org/wikipedia/commons/0/00/Torifuda_073.svg'),
  (74, 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Torifuda_074.svg'),
  (75, 'https://upload.wikimedia.org/wikipedia/commons/7/71/Torifuda_075.svg'),
  (76, 'https://upload.wikimedia.org/wikipedia/commons/d/de/Torifuda_076.svg'),
  (77, 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Torifuda_077.svg'),
  (78, 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Torifuda_078.svg'),
  (79, 'https://upload.wikimedia.org/wikipedia/commons/0/01/Torifuda_079.svg'),
  (80, 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Torifuda_080.svg'),
  (81, 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Torifuda_081.svg'),
  (82, 'https://upload.wikimedia.org/wikipedia/commons/8/84/Torifuda_082.svg'),
  (83, 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Torifuda_083.svg'),
  (84, 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Torifuda_084.svg'),
  (85, 'https://upload.wikimedia.org/wikipedia/commons/9/99/Torifuda_085.svg'),
  (86, 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Torifuda_086.svg'),
  (87, 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Torifuda_087.svg'),
  (88, 'https://upload.wikimedia.org/wikipedia/commons/2/28/Torifuda_088.svg'),
  (89, 'https://upload.wikimedia.org/wikipedia/commons/7/77/Torifuda_089.svg'),
  (90, 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Torifuda_090.svg'),
  (91, 'https://upload.wikimedia.org/wikipedia/commons/3/34/Torifuda_091.svg'),
  (92, 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Torifuda_092.svg'),
  (93, 'https://upload.wikimedia.org/wikipedia/commons/1/13/Torifuda_093.svg'),
  (94, 'https://upload.wikimedia.org/wikipedia/commons/b/be/Torifuda_094.svg'),
  (95, 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Torifuda_095.svg'),
  (96, 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Torifuda_096.svg'),
  (97, 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Torifuda_097.svg'),
  (98, 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Torifuda_098.svg'),
  (99, 'https://upload.wikimedia.org/wikipedia/commons/2/20/Torifuda_099.svg'),
  (100, 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Torifuda_100.svg')
  ) AS t(number, url)
 WHERE poems.number = t.number;
