-- 百人一首100首のデータ（仕様22.1 poems テーブル）
--
-- データの出どころ:
--   ・歌の本文・読み仮名・作者・絵札画像: https://api.aoikujira.com/hyakunin/get2.php?fmt=json
--   ・決まり字: apps/api/src/onboarding-backend/kimariji/kimariji.service.ts
--
-- 実行方法（apps/api ディレクトリで）:
--   set -a; . ./.env; set +a
--   PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
--     -f src/chihaya/sql/seed_poems.sql
--
-- 何度実行しても結果が同じになるよう、番号が重複したら更新する形にしている
-- （ON CONFLICT ... DO UPDATE）。

INSERT INTO poems (number, kimariji, kami, shimo, kami_kana, shimo_kana, author, author_kana, image_url) VALUES
  (1, 'あきの', '秋の田の かりほの庵の 苫をあらみ', '我が衣手は 露にぬれつつ', 'あきのたの かりほのいほの とまをあらみ', 'わがころもでは つゆにぬれつつ', '天智天皇', 'てんじてんのう', 'https://upload.wikimedia.org/wikipedia/commons/0/04/Hyakuninisshu_001.jpg'),
  (2, 'はるす', '春過ぎて 夏来にけらし 白妙の', '衣ほすてふ 天の香具山', 'はるすぎて なつきにけらし しろたへの', 'ころもほすてふ あまのかぐやま', '持統天皇', 'じとうてんのう', 'https://upload.wikimedia.org/wikipedia/commons/9/95/Hyakuninisshu_002.jpg'),
  (3, 'あし', 'あしびきの 山鳥の尾の しだり尾の', 'ながながし夜を ひとりかも寝む', 'あしびきの やまどりのをの しだりをの', 'ながながしよを ひとりかもねむ', '柿本人麻呂', 'かきのもとのひとまろ', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Hyakuninisshu_003.jpg'),
  (4, 'たご', '田子の浦に うちいでてみれば 白妙の', '富士の高嶺に 雪は降りつつ', 'たごのうらに うちいでてみれば しろたへの', 'ふじのたかねに ゆきはふりつつ', '山部赤人', 'やまべのあかひと', 'https://upload.wikimedia.org/wikipedia/commons/3/37/Hyakuninisshu_004.jpg'),
  (5, 'おく', '奥山に もみぢふみわけ なく鹿の', '声聞く時ぞ 秋はかなしき', 'おくやまに もみぢふみわけ なくしかの', 'こゑきくときぞ あきはかなしき', '猿丸太夫', 'さるまるだゆう', 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Hyakuninisshu_005.jpg'),
  (6, 'かさ', 'かささぎの 渡せる橋に おく霜の', '白きをみれば 夜ぞふけにける', 'かささぎの わたせるはしに おくしもの', 'しろきをみれば よぞふけにける', '中納言家持', 'ちゅうなごんやかもち', 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Hyakuninisshu_006.jpg'),
  (7, 'あまの', '天の原 ふりさけみれば 春日なる', '三笠の山に いでし月かも', 'あまのはら ふりさけみれば かすがなる', 'みかさのやまに いでしつきかも', '阿倍仲麻呂', 'あべのなかまろ', 'https://upload.wikimedia.org/wikipedia/commons/4/46/Hyakuninisshu_007.jpg'),
  (8, 'わがい', 'わが庵は 都のたつみ しかぞすむ', '世をうぢ山と 人はいふなり', 'わがいほは みやこのたつみ しかぞすむ', 'よをうぢやまと ひとはいふなり', '喜撰法師', 'きせんほうし', 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Hyakuninisshu_008.jpg'),
  (9, 'はなの', '花の色は うつりにけりな いたづらに', 'わが身よにふる ながめせしまに', 'はなのいろは うつりにけりな いたづらに', 'わがみよにふる ながめせしまに', '小野小町', 'おののこまち', 'https://upload.wikimedia.org/wikipedia/commons/9/94/Hyakuninisshu_009.jpg'),
  (10, 'これ', 'これやこの 行くも帰るも わかれては', 'しるもしらぬも 逢坂の関', 'これやこの ゆくもかへるも わかれては', 'しるもしらぬも あふさかのせき', '蝉丸', 'せみまる', 'https://upload.wikimedia.org/wikipedia/commons/2/29/Hyakuninisshu_010.jpg'),
  (11, 'わたのはらや', 'わたの原 八十島かけて こぎいでぬと', '人にはつげよ あまのつり舟', 'わたのはら やそしまかけて こぎいでぬと', 'ひとにはつげよ あまのつりぶね', '参議篁', 'さんぎたかむら', 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Hyakuninisshu_011.jpg'),
  (12, 'あまつ', '天つ風 雲のかよひ路 吹きとぢよ', 'をとめの姿 しばしとどめむ', 'あまつかぜ くものかよひぢ ふきとぢよ', 'をとめのすがた しばしとどめむ', '僧正遍昭', 'そうじょうへんじょう', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Hyakuninisshu_012.jpg'),
  (13, 'つく', 'つくばねの 峰よりおつる みなの川', '恋ぞつもりて 淵となりぬる', 'つくばねの みねよりおつる みなのがは', 'こひぞつもりて ふちとなりぬる', '陽成院', 'ようぜいいん', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Hyakuninisshu_013.jpg'),
  (14, 'みち', 'みちのくの しのぶもぢずり 誰ゆゑに', 'みだれそめにし 我ならなくに', 'みちのくの しのぶもぢずり たれゆゑに', 'みだれそめにし われならなくに', '河原左大臣', 'かわらのさだいじん', 'https://upload.wikimedia.org/wikipedia/commons/9/94/Hyakuninisshu_014.jpg'),
  (15, 'きみがためは', '君がため 春の野に出でて 若菜つむ', 'わが衣手に 雪はふりつつ', 'きみがため はるののにいでて わかなつむ', 'わがころもでに ゆきはふりつつ', '光孝天皇', 'こうこうてんのう', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Hyakuninisshu_015.jpg'),
  (16, 'たち', '立ちわかれ いなばの山の 峰に生ふる', 'まつとし聞かば いまかへりこむ', 'たちわかれ いなばのやまの みねにおふる', 'まつとしきかば いまかへりこむ', '中納言行平', 'ちゅうなごんゆきひら', 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Hyakuninisshu_016.jpg'),
  (17, 'ちは', 'ちはやぶる 神代もきかず 竜田川', 'からくれなゐに 水くくるとは', 'ちはやぶる かみよもきかず たつたがは', 'からくれなゐに みづくくるとは', '在原業平朝臣', 'ありわらのなりひらあそん', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Hyakuninisshu_017.jpg'),
  (18, 'す', '住の江の 岸による波 よるさへや', '夢のかよひ路 人目よくらむ', 'すみのえの きしによるなみ よるさへや', 'ゆめのかよひぢ ひとめよくらむ', '藤原敏行朝臣', 'ふじわらのとしゆきあそん', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Hyakuninisshu_018.jpg'),
  (19, 'なにわが', '難波潟 みじかき蘆の ふしのまも', 'あはでこの世を すぐしてよとや', 'なにはがた みじかきあしの ふしのまも', 'あはでこのよを すぐしてよとや', '伊勢', 'いせ', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Hyakuninisshu_019.jpg'),
  (20, 'わび', 'わびぬれば いまはたおなじ 難波なる', '身をつくしても あはむとぞ思ふ', 'わびぬれば いまはたおなじ なにはなる', 'みをつくしても あはむとぞおもふ', '元良親王', 'もとよししんのう', 'https://upload.wikimedia.org/wikipedia/commons/9/97/Hyakuninisshu_020.jpg'),
  (21, 'いまこ', '今こむと いひしばかりに 長月の', '有明の月を まちいでつるかな', 'いまこむと いひしばかりに ながつきの', 'ありあけのつきを まちいでつるかな', '素性法師', 'そせいほうし', 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Hyakuninisshu_021.jpg'),
  (22, 'ふ', '吹くからに 秋の草木の しをるれば', 'むべ山風を 嵐といふらむ', 'ふくからに あきのくさきの しをるれば', 'むべやまかぜを あらしといふらむ', '文屋康秀', 'ふんやのやすひで', 'https://upload.wikimedia.org/wikipedia/commons/1/11/Hyakuninisshu_022.jpg'),
  (23, 'つき', '月みれば ちぢにものこそ かなしけれ', 'わが身一つの 秋にはあらねど', 'つきみれば ちぢにものこそ かなしけれ', 'わがみひとつの あきにはあらねど', '大江千里', 'おおえのちさと', 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Hyakuninisshu_023.jpg'),
  (24, 'この', 'このたびは ぬさもとりあへず 手向山', 'もみぢのにしき 神のまにまに', 'このたびは ぬさもとりあへず たむけやま', 'もみぢのにしき かみのまにまに', '菅家', 'かんけ', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Hyakuninisshu_024.jpg'),
  (25, 'なにし', '名にし負はば 逢坂山の さねかづら', '人にしられで 来るよしもがな', 'なにしおはば あふさかやまの さねかづら', 'ひとにしられで くるよしもがな', '三条右大臣', 'さんじょうのうだいじん', 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Hyakuninisshu_025.jpg'),
  (26, 'おぐ', '小倉山 峰のもみぢ葉 心あらば', 'いまひとたびの みゆきまたなむ', 'をぐらやま みねのもみぢば こころあらば', 'いまひとたびの みゆきまたなむ', '貞信公', 'ていしんこう', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Hyakuninisshu_026.jpg'),
  (27, 'みかの', 'みかの原 わきて流るる いづみ川', 'いつみきとてか 恋しかるらむ', 'みかのはら わきてながるる いづみがは', 'いつみきとてか こひしかるらむ', '中納言兼輔', 'ちゅうなごんかねすけ', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Hyakuninisshu_027.jpg'),
  (28, 'やまざ', '山里は 冬ぞさびしさ まさりける', '人目も草も かれぬと思へば', 'やまざとは ふゆぞさびしさ まさりける', 'ひとめもくさも かれぬとおもへば', '源宗行朝臣', 'みなもとのむねゆきあそん', 'https://upload.wikimedia.org/wikipedia/commons/a/af/Hyakuninisshu_028.jpg'),
  (29, 'こころあ', '心当てに 折らばや折らむ 初霜の', 'おきまどはせる 白菊の花', 'こころあてに をらばやをらむ はつしもの', 'おきまどはせる しらぎくのはな', '凡河内躬恒', 'おおしこうちのみつね', 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Hyakuninisshu_029.jpg'),
  (30, 'ありあ', '有明の つれなく見えし 別れより', 'あかつきばかり うきものはなし', 'ありあけの つれなくみえし わかれより', 'あかつきばかり うきものはなし', '壬生忠岑', 'みぶのただみね', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Hyakuninisshu_030.jpg'),
  (31, 'あさぼらけあ', '朝ぼらけ 有明の月と 見るまでに', '吉野の里に 降れる白雪', 'あさぼらけ ありあけのつきと みるまでに', 'よしののさとに ふれるしらゆき', '坂上是則', 'さかのうえのこれのり', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Hyakuninisshu_031.jpg'),
  (32, 'やまが', '山川に 風のかけたる しがらみは', 'ながれもあへぬ もみぢなりけり', 'やまがはに かぜのかけたる しがらみは', 'ながれもあへぬ もみぢなりけり', '春道列樹', 'はるみちのつらき', 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Hyakuninisshu_032.jpg'),
  (33, 'ひさ', '久方の 光のどけき 春の日に', 'しづ心なく 花の散るらむ', 'ひさかたの ひかりのどけき はるのひに', 'しづこころなく はなのちるらむ', '紀友則', 'きのとものり', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Hyakuninisshu_033.jpg'),
  (34, 'たれ', '誰をかも しる人にせむ 高砂の', '松も昔の 友ならなくに', 'たれをかも しるひとにせむ たかさごの', 'まつもむかしの ともならなくに', '藤原興風', 'ふじわらのおきかぜ', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Hyakuninisshu_034.jpg'),
  (35, 'ひとは', '人はいさ 心も知らず ふるさとは', '花ぞ昔の 香に匂ひける', 'ひとはいさ こころもしらず ふるさとは', 'はなぞむかしの かににほひける', '紀貫之', 'きのつらゆき', 'https://upload.wikimedia.org/wikipedia/commons/3/32/Hyakuninisshu_035.jpg'),
  (36, 'なつ', '夏の夜は まだ宵ながら あけぬるを', '雲のいづこに 月やどるらむ', 'なつのよは まだよひながら あけぬるを', 'くものいづこに つきやどるらむ', '清原深養父', 'きよはらのふかやぶ', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Hyakuninisshu_036.jpg'),
  (37, 'しら', '白露に 風の吹きしく 秋の野は', 'つらぬきとめぬ 玉ぞ散りける', 'しらつゆに かぜのふきしく あきののは', 'つらぬきとめぬ たまぞちりける', '文屋朝康', 'ふんやのあさやす', 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Hyakuninisshu_037.jpg'),
  (38, 'わすら', '忘らるる 身をば思はず ちかひてし', '人の命の 惜しくもあるかな', 'わすらるる みをばおもはず ちかひてし', 'ひとのいのちの をしくもあるかな', '右近', 'うこん', 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Hyakuninisshu_038.jpg'),
  (39, 'あさじ', '浅茅生の 小野の篠原 しのぶれど', 'あまりてなどか 人の恋しき', 'あさぢふの をののしのはら しのぶれど', 'あまりてなどか ひとのこひしき', '参議等', 'さんぎひとし', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Hyakuninisshu_039.jpg'),
  (40, 'しの', 'しのぶれど 色に出でにけり 我が恋は', '物や思ふと 人の問ふまで', 'しのぶれど いろにいでにけり わがこひは', 'ものやおもふと ひとのとふまで', '平兼盛', 'たいらのかねもり', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Hyakuninisshu_040.jpg'),
  (41, 'こい', '恋すてふ 我が名はまだき 立ちにけり', '人しれずこそ 思ひそめしか', 'こひすてふ わがなはまだき たちにけり', 'ひとしれずこそ おもひそめしか', '壬生忠見', 'みぶのただみ', 'https://upload.wikimedia.org/wikipedia/commons/6/61/Hyakuninisshu_041.jpg'),
  (42, 'ちぎりき', 'ちぎりきな かたみに袖を しぼりつつ', '末の松山 波こさじとは', 'ちぎりきな かたみにそでを しぼりつつ', 'すゑのまつやま なみこさじとは', '清原元輔', 'きよはらのもとすけ', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Hyakuninisshu_042.jpg'),
  (43, 'あい', 'あひみての のちの心に くらぶれば', '昔は物を 思はざりけり', 'あひみての のちのこころに くらぶれば', 'むかしはものを おもはざりけり', '権中納言敦忠', 'ごんちゅうなごんあつただ', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Hyakuninisshu_043.jpg'),
  (44, 'おおこ', 'あふことの たえてしなくば なかなかに', '人をも身をも 恨みざらまし', 'あふことの たえてしなくば なかなかに', 'ひとをもみをも うらみざらまし', '中納言朝忠', 'ちゅうなごんあさただ', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Hyakuninisshu_044.jpg'),
  (45, 'あわれ', 'あはれとも いふべき人は 思ほえで', '身のいたづらに なりぬべきかな', 'あはれとも いふべきひとは おもほえで', 'みのいたづらに なりぬべきかな', '謙徳公', 'けんとくこう', 'https://upload.wikimedia.org/wikipedia/commons/4/40/Hyakuninisshu_045.jpg'),
  (46, 'ゆら', '由良のとを 渡る舟人 かぢをたえ', 'ゆくへも知らぬ 恋の道かな', 'ゆらのとを わたるふなびと かぢをたえ', 'ゆくへもしらぬ こひのみちかな', '曽禰好忠', 'そねのよしただ', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Hyakuninisshu_046.jpg'),
  (47, 'やえ', '八重むぐら しげれる宿の さびしきに', '人こそ見えね 秋は来にけり', 'やへむぐら しげれるやどの さびしきに', 'ひとこそみえね あきはきにけり', '恵慶法師', 'えぎょうほうし', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Hyakuninisshu_047.jpg'),
  (48, 'かぜを', '風をいたみ 岩うつ波の おのれのみ', 'くだけて物を 思ふころかな', 'かぜをいたみ いはうつなみの おのれのみ', 'くだけてものを おもふころかな', '源重之', 'みなもとのしげゆき', 'https://upload.wikimedia.org/wikipedia/commons/9/97/Hyakuninisshu_048.jpg'),
  (49, 'みかき', 'みかきもり 衛士のたく火の 夜はもえ', '昼は消えつつ 物をこそ思へ', 'みかきもり ゑじのたくひの よるはもえ', 'ひるはきえつつ ものをこそおもへ', '大中臣能宣朝臣', 'おおなかとみのよしのぶあそん', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Hyakuninisshu_049.jpg'),
  (50, 'きみがためお', '君がため 惜しからざりし いのちさへ', '長くもがなと 思ひけるかな', 'きみがため をしからざりし いのちさへ', 'ながくもがなと おもひけるかな', '藤原義孝', 'ふじわらのよしたか', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Hyakuninisshu_050.jpg'),
  (51, 'かく', 'かくとだに えやはいぶきの さしも草', 'さしもしらじな もゆる思ひを', 'かくとだに えやはいぶきの さしもぐさ', 'さしもしらじな もゆるおもひを', '藤原実方朝臣', 'ふじわらのさねかたあそん', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Hyakuninisshu_051.jpg'),
  (52, 'あけ', 'あけぬれば 暮るるものとは 知りながら', 'なほうらめしき 朝ぼらけかな', 'あけぬれば くるるものとは しりながら', 'なほうらめしき あさぼらけかな', '藤原道信朝臣', 'ふじわらのみちのぶあそん', 'https://upload.wikimedia.org/wikipedia/commons/0/08/Hyakuninisshu_052.jpg'),
  (53, 'なげき', 'なげきつつ ひとりぬる夜の あくるまは', 'いかに久しき ものとかはしる', 'なげきつつ ひとりぬるよの あくるまは', 'いかにひさしき ものとかはしる', '右大将道綱母', 'うだいしょうみちつなのはは', 'https://upload.wikimedia.org/wikipedia/commons/0/02/Hyakuninisshu_053.jpg'),
  (54, 'わすれ', '忘れじの ゆく末までは かたければ', '今日をかぎりの いのちともがな', 'わすれじの ゆくすゑまでは かたければ', 'けふをかぎりの いのちともがな', '儀同三司母', 'ぎどうさんしのはは', 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Hyakuninisshu_054.jpg'),
  (55, 'たき', '滝の音は たえて久しく なりぬれど', '名こそ流れて なほ聞こえけれ', 'たきのおとは たえてひさしく なりぬれど', 'なこそながれて なほきこえけれ', '大納言公任', 'だいなごんきんとう', 'https://upload.wikimedia.org/wikipedia/commons/3/31/Hyakuninisshu_055.jpg'),
  (56, 'あらざ', 'あらざらむ この世のほかの 思ひ出に', 'いまひとたびの あふこともがな', 'あらざらむ このよのほかの おもひでに', 'いまひとたびの あふこともがな', '和泉式部', 'いずみしきぶ', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Hyakuninisshu_056.jpg'),
  (57, 'め', 'めぐりあひて 見しやそれとも わかぬまに', '雲がくれにし 夜半の月かな', 'めぐりあひて みしやそれとも わかぬまに', 'くもがくれにし よはのつきかな', '紫式部', 'むらさきしきぶ', 'https://upload.wikimedia.org/wikipedia/commons/1/13/Hyakuninisshu_057.jpg'),
  (58, 'ありま', 'ありま山 ゐなの笹原 風吹けば', 'いでそよ人を 忘れやはする', 'ありまやま ゐなのささはら かぜふけば', 'いでそよひとを わすれやはする', '大弐三位', 'だいにのさんみ', 'https://upload.wikimedia.org/wikipedia/commons/7/71/Hyakuninisshu_058.jpg'),
  (59, 'やす', 'やすらはで 寝なましものを さ夜ふけて', 'かたぶくまでの 月を見しかな', 'やすらはで ねなましものを さよふけて', 'かたぶくまでの つきをみしかな', '赤染衛門', 'あかぞめえもん', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Hyakuninisshu_059.jpg'),
  (60, 'おおえ', '大江山 いく野の道の 遠ければ', 'まだふみもみず 天の橋立', 'おほえやま いくののみちの とほければ', 'まだふみもみず あまのはしだて', '小式部内侍', 'こしきぶのないし', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Hyakuninisshu_060.jpg'),
  (61, 'いにし', 'いにしへの 奈良の都の 八重桜', 'けふ九重に 匂ひぬるかな', 'いにしへの ならのみやこの やへざくら', 'けふここのへに にほひぬるかな', '伊勢大輔', 'いせのたいふ', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Hyakuninisshu_061.jpg'),
  (62, 'よを', '夜をこめて 鳥のそらねは はかるとも', 'よに逢坂の 関はゆるさじ', 'よをこめて とりのそらねは はかるとも', 'よにあふさかの せきはゆるさじ', '清少納言', 'せいしょうなごん', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Hyakuninisshu_062.jpg'),
  (63, 'いまは', 'いまはただ 思ひ絶えなむ とばかりを', '人づてならで 言ふよしもがな', 'いまはただ おもひたえなむ とばかりを', 'ひとづてならで いふよしもがな', '左京大夫道雅', 'さきょうのだいぶみちまさ', 'https://upload.wikimedia.org/wikipedia/commons/b/be/Hyakuninisshu_063.jpg'),
  (64, 'あさぼらけう', '朝ぼらけ 宇治の川霧 絶え絶えに', 'あらはれわたる 瀬々の網代木', 'あさぼらけ うぢのかはぎり たえだえに', 'あらはれわたる せぜのあじろぎ', '権中納言定頼', 'ごんちゅうなごんさだより', 'https://upload.wikimedia.org/wikipedia/commons/2/25/Hyakuninisshu_064.jpg'),
  (65, 'うら', 'うらみわび ほさぬ袖だに あるものを', '恋にくちなむ 名こそをしけれ', 'うらみわび ほさぬそでだに あるものを', 'こひにくちなむ なこそをしけれ', '相模', 'さがみ', 'https://upload.wikimedia.org/wikipedia/commons/5/51/Hyakuninisshu_065.jpg'),
  (66, 'もろ', 'もろともに あはれと思へ 山桜', '花よりほかに 知る人もなし', 'もろともに あはれとおもへ やまざくら', 'はなよりほかに しるひともなし', '前大僧正行尊', 'さきのだいそうじょうぎょうそん', 'https://upload.wikimedia.org/wikipedia/commons/2/26/Hyakuninisshu_066.jpg'),
  (67, 'はるの', '春の夜の 夢ばかりなる 手枕に', 'かひなくたたむ 名こそをしけれ', 'はるのよの ゆめばかりなる たまくらに', 'かひなくたたむ なこそをしけれ', '周防内侍', 'すおうのないし', 'https://upload.wikimedia.org/wikipedia/commons/9/93/Hyakuninisshu_067.jpg'),
  (68, 'こころに', '心にも あらでうき世に ながらへば', '恋しかるべき 夜半の月かな', 'こころにも あらでうきよに ながらへば', 'こひしかるべき よはのつきかな', '三条院', 'さんじょういん', 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Hyakuninisshu_068.jpg'),
  (69, 'あらし', 'あらし吹く み室の山の もみぢばは', '竜田の川の 錦なりけり', 'あらしふく みむろのやまの もみぢばは', 'たつたのかはの にしきなりけり', '能因法師', 'のういんほうし', 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Hyakuninisshu_069.jpg'),
  (70, 'さ', 'さびしさに 宿を立ち出でて ながむれば', 'いづくもおなじ 秋の夕ぐれ', 'さびしさに やどをたちいでて ながむれば', 'いづくもおなじ あきのゆふぐれ', '良選法師', 'りょうぜんほうし', 'https://upload.wikimedia.org/wikipedia/commons/7/75/Hyakuninisshu_070.jpg'),
  (71, 'ゆう', '夕されば 門田の稲葉 おとづれて', '蘆のまろやに 秋風ぞ吹く', 'ゆふされば かどたのいなば おとづれて', 'あしのまろやに あきかぜぞふく', '大納言経信', 'だいなごんつねのぶ', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Hyakuninisshu_071.jpg'),
  (72, 'おと', '音に聞く 高師の浜の あだ波は', 'かけじや袖の ぬれもこそすれ', 'おとにきく たかしのはまの あだなみは', 'かけじやそでの ぬれもこそすれ', '祐子内親王家紀伊', 'ゆうしないしんのうけのきい', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Hyakuninisshu_072.jpg'),
  (73, 'たか', '高砂の をのへのさくら さきにけり', 'とやまのかすみ たたずもあらなむ', 'たかさごの をのへのさくら さきにけり', 'とやまのかすみ たたずもあらなむ', '前権中納言匡房', 'さきのごんちゅうなごんまさふさ', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Hyakuninisshu_073.jpg'),
  (74, 'うか', '憂かりける 人を初瀬の 山おろしよ', 'はげしかれとは 祈らぬものを', 'うかりける ひとをはつせの やまおろしよ', 'はげしかれとは いのらぬものを', '源俊頼朝臣', 'みなもとのとしよりあそん', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Hyakuninisshu_074.jpg'),
  (75, 'ちぎりお', 'ちぎりおきし させもが露を いのちにて', 'あはれ今年の 秋もいぬめり', 'ちぎりおきし させもがつゆを いのちにて', 'あはれことしの あきもいぬめり', '藤原基俊', 'ふじわらのもととし', 'https://upload.wikimedia.org/wikipedia/commons/5/55/Hyakuninisshu_075.jpg'),
  (76, 'わたのはらこ', 'わたの原 こぎいでてみれば 久方の', '雲いにまがふ 沖つ白波', 'わたのはら こぎいでてみれば ひさかたの', 'くもゐにまがふ おきつしらなみ', '法性寺入道前関白太政大臣', 'ほつしょうじにゅうどうさきの かんぱくだいじょうだいじん', 'https://upload.wikimedia.org/wikipedia/commons/d/da/Hyakuninisshu_076.jpg'),
  (77, 'せ', '瀬をはやみ 岩にせかるる 滝川の', 'われても末に あはむとぞ思ふ', 'せをはやみ いはにせかるる たきがはの', 'われてもすゑに あはむとぞおもふ', '崇徳院', 'すとくいん', 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Hyakuninisshu_077.jpg'),
  (78, 'あわじ', '淡路島 かよふ千鳥の 鳴く声に', '幾夜ねざめぬ 須磨の関守', 'あはぢしま かよふちどりの なくこゑに', 'いくよねざめぬ すまのせきもり', '源兼昌', 'みなもとのかねまさ', 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Hyakuninisshu_078.jpg'),
  (79, 'あきか', '秋風に たなびく雲の たえ間より', 'もれいづる月の 影のさやけさ', 'あきかぜに たなびくくもの たえまより', 'もれいづるつきの かげのさやけさ', '左京大夫顕輔', 'さきょうのだいぶあきすけ', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Hyakuninisshu_079.jpg'),
  (80, 'ながか', '長からむ 心もしらず 黒髪の', 'みだれてけさは 物をこそ思へ', 'ながからむ こころもしらず くろかみの', 'みだれてけさは ものをこそおもへ', '待賢門院堀河', 'たいけんもんいんほりかわ', 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Hyakuninisshu_080.jpg'),
  (81, 'ほ', 'ほととぎす 鳴きつる方を ながむれば', 'ただありあけの 月ぞ残れる', 'ほととぎす なきつるかたを ながむれば', 'ただありあけの つきぞのこれる', '後徳大寺左大臣', 'ごとくだいじさだいじん', 'https://upload.wikimedia.org/wikipedia/commons/d/da/Hyakuninisshu_081.jpg'),
  (82, 'おも', '思ひわび さてもいのちは あるものを', '憂きにたへぬは 涙なりけり', 'おもひわび さてもいのちは あるものを', 'うきにたへぬは なみだなりけり', '道因法師', 'どういんほうし', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Hyakuninisshu_082.jpg'),
  (83, 'よのなかよ', '世の中よ 道こそなけれ 思ひ入る', '山の奥にも 鹿ぞ鳴くなる', 'よのなかよ みちこそなけれ おもひいる', 'やまのおくにも しかぞなくなる', '皇太后宮大夫俊成', 'こうたいごうぐうのだいぶしゅんぜい', 'https://upload.wikimedia.org/wikipedia/commons/b/be/Hyakuninisshu_083.jpg'),
  (84, 'ながら', 'ながらへば またこのごろや しのばれむ', '憂しと見し世ぞ 今は恋しき', 'ながらへば またこのごろや しのばれむ', 'うしとみしよぞ いまはこひしき', '藤原清輔朝臣', 'ふじわらのきよすけあそん', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Hyakuninisshu_084.jpg'),
  (85, 'よも', '夜もすがら 物思ふころは 明けやらで', '閨のひまさへ つれなかりけり', 'よもすがら ものおもふころは あけやらで', 'ねやのひまさへ つれなかりけり', '俊恵法師', 'しゅんえほうし', 'https://upload.wikimedia.org/wikipedia/commons/0/06/Hyakuninisshu_085.jpg'),
  (86, 'なげけ', 'なげけとて 月やは物を 思はする', 'かこち顔なる わが涙かな', 'なげけとて つきやはものを おもはする', 'かこちがほなる わがなみだかな', '西行法師', 'さいぎょうほうし', 'https://upload.wikimedia.org/wikipedia/commons/6/61/Hyakuninisshu_086.jpg'),
  (87, 'む', '村雨の 露もまだひぬ まきの葉に', '霧たちのぼる 秋の夕ぐれ', 'むらさめの つゆもまだひぬ まきのはに', 'きりたちのぼる あきのゆふぐれ', '寂蓮法師', 'じゃくれんほうし', 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Hyakuninisshu_087.jpg'),
  (88, 'なにわえ', '難波江の 蘆のかりねの ひとよゆゑ', 'みをつくしてや 恋ひわたるべき', 'なにはえの あしのかりねの ひとよゆゑ', 'みをつくしてや こひわたるべき', '皇嘉門院別当', 'こうかもんいんのべつとう', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Hyakuninisshu_088.jpg'),
  (89, 'たま', '玉の緒よ たえなばたえね ながらへば', '忍ぶることの 弱りもぞする', 'たまのをよ たえなばたえね ながらへば', 'しのぶることの よわりもぞする', '式子内親王', 'しきしないしんのう', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Hyakuninisshu_089.jpg'),
  (90, 'みせ', '見せばやな 雄島のあまの 袖だにも', 'ぬれにぞぬれし 色はかはらず', 'みせばやな をじまのあまの そでだにも', 'ぬれにぞぬれし いろはかはらず', '殷富門院大輔', 'いんぶもんいんのたいふ', 'https://upload.wikimedia.org/wikipedia/commons/8/82/Hyakuninisshu_090.jpg'),
  (91, 'きり', 'きりぎりす 鳴くや霜夜の さむしろに', '衣かたしき ひとりかも寝む', 'きりぎりす なくやしもよの さむしろに', 'ころもかたしき ひとりかもねむ', '後京極摂政前太政大臣', 'ごきょうごくせっしょうさきのだいじょうだいじん', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Hyakuninisshu_091.jpg'),
  (92, 'わがそ', 'わが袖は 潮干にみえぬ 沖の石の', '人こそしらね かわくまもなし', 'わがそでは しほひにみえぬ おきのいしの', 'ひとこそしらね かわくまもなし', '二条院讃岐', 'にじょういんのさぬき', 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Hyakuninisshu_092.jpg'),
  (93, 'よのなかは', '世の中は つねにもがもな なぎさこぐ', 'あまの小舟の 綱手かなしも', 'よのなかは つねにもがもな なぎさこぐ', 'あまのをぶねの つなでかなしも', '鎌倉右大臣', 'かまくらのうだいじん', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Hyakuninisshu_093.jpg'),
  (94, 'みよ', 'み吉野の 山の秋風 さ夜ふけて', 'ふるさと寒く 衣うつなり', 'みよしのの やまのあきかぜ さよふけて', 'ふるさとさむく ころもうつなり', '参議雅経', 'さんぎまさつね', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Hyakuninisshu_094.jpg'),
  (95, 'おおけ', 'おほけなく うき世の民に おほふかな', 'わがたつ杣に 墨染の袖', 'おほけなく うきよのたみに おほふかな', 'わがたつそまに すみぞめのそで', '前大僧正慈円', 'さきのだいそうじょうじえん', 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Hyakuninisshu_095.jpg'),
  (96, 'はなさ', '花さそふ 嵐の庭の 雪ならで', 'ふりゆくものは わが身なりけり', 'はなさそふ あらしのにはの ゆきならで', 'ふりゆくものは わがみなりけり', '入道前太政大臣', 'にゅうどうさきのだいじょうだいじん', 'https://upload.wikimedia.org/wikipedia/commons/8/83/Hyakuninisshu_096.jpg'),
  (97, 'こぬ', 'こぬ人を まつほの浦の 夕なぎに', '焼くやもしほの 身もこがれつつ', 'こぬひとを まつほのうらの ゆふなぎに', 'やくやもしほの みもこがれつつ', '権中納言定家', 'ごんちゅうなごんていか', 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Hyakuninisshu_097.jpg'),
  (98, 'かぜそ', '風そよぐ ならの小川の 夕ぐれは', 'みそぎぞ夏の しるしなりける', 'かぜそよぐ ならのをがはの ゆふぐれは', 'みそぎぞなつの しるしなりける', '従二位家隆', 'じゅうにいいえたか', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Hyakuninisshu_098.jpg'),
  (99, 'ひとも', '人もをし 人もうらめし あぢきなく', '世を思ふゆゑに 物思ふ身は', 'ひともをし ひともうらめし あぢきなく', 'よをおもふゆゑに ものおもふみは', '後鳥羽院', 'ごとばいん', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Hyakuninisshu_099.jpg'),
  (100, 'もも', 'ももしきや ふるき軒ばの しのぶにも', 'なほあまりある 昔なりけり', 'ももしきや ふるきのきばの しのぶにも', 'なほあまりある むかしなりけり', '順徳院', 'じゅんとくいん', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Hyakuninisshu_100.jpg')
ON CONFLICT (number) DO UPDATE SET
  kimariji    = EXCLUDED.kimariji,
  kami        = EXCLUDED.kami,
  shimo       = EXCLUDED.shimo,
  kami_kana   = EXCLUDED.kami_kana,
  shimo_kana  = EXCLUDED.shimo_kana,
  author      = EXCLUDED.author,
  author_kana = EXCLUDED.author_kana,
  image_url   = EXCLUDED.image_url,
  updated_at  = now();
